src/SignInAppTest/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Text;
using DaVinciCollegeAuthenticationService.Models;
using DaVinciCollegeAuthenticationService.Data;
using Microsoft.AspNetCore.Identity;
using DaVinciCollegeAuthenticationService.Services;
using DaVinciCollegeAuthenticationService.Models.AdminViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace DaVinciCollegeAuthenticationService.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public AdminPanelController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
            _signInManager = signInManager;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ImportUsersFromCSV()
        {
            return View(new ImportUsersFromCSVPostModel() { SuccessType = SuccessType.None });
        }

        [HttpPost]
        public async Task<IActionResult> ImportUsersFromCSVPost(IFormFile file)
        {
            var reader = new BinaryReader(file.OpenReadStream());
            var fileBytes = reader.ReadBytes((int)file.Length);

            var fileDataResult = Encoding.UTF8.GetString(fileBytes);
            var rows = new List<string>();
            foreach (var item in fileDataResult.Split('"'))
            {
                if (item.Length <= 1) continue;

                int testResult;
                if (int.TryParse(item[1].ToString(), out testResult))
                    rows.Add(item);
            }

            var newUsers = (from row in rows
                            select row.Split(';')
                into splittedRow
                            let userName = splittedRow[0]
                            let firstName = splittedRow[1]
                            let middleName = splittedRow[2]
                            let lastName = splittedRow[3]
                            select new ApplicationUser
                            {
                                Lastname = lastName,
                                Prefix = middleName,
                                Firstname = firstName,
                                UserName = userName,
                                Email = userName + "@mydavinci.nl"
                                //Only works for students with an email like this 99027705@mydavinci.nl
                            }).ToList();

            foreach (var user in newUsers)
            {
                var checkUser = _context.ApplicationUser.FirstOrDefault(a => a.UserName == user.UserName);
                if (checkUser == null)//User doesnt exist yet
                {
                    var result = await _userManager.CreateAsync(user);
                    if (result.Succeeded)
                    {
                        continue;
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(error.Code, error.Description);
                    }

                    return View(nameof(ImportUsersFromCSV), new ImportUsersFromCSVPostModel() { SuccessType = SuccessType.Failed });
                }
                else
                {
                    checkUser.Lastname = user.Lastname;
                    checkUser.Prefix = user.Prefix;
                    checkUser.Firstname = user.Firstname;
                    checkUser.UserName = user.UserName;
                    await _context.SaveChangesAsync();
                }
            }

            return View(nameof(ImportUsersFromCSV), new ImportUsersFromCSVPostModel() { SuccessType = SuccessType.Succeeded });
        }
    }
}

src/SignInAppTest/Controllers/ApplicationController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DaVinciCollegeAuthenticationService.Data;
using DaVinciCollegeAuthenticationService.Models;
using DaVinciCollegeAuthenticationService.Models.ApplicationViewModels;
using DaVinciCollegeAuthenticationService.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;

namespace DaVinciCollegeAuthenticationService.Controllers
{
    [Authorize]
    public class ApplicationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ITokenProvider _tokenProvider;
        private readonly UserManager<ApplicationUser> _userManager;

        public ApplicationController(UserManager<ApplicationUser> userManager, ApplicationDbContext context,
            ITokenProvider tokenProvider)
        {
            _context = context;
            _userManager = userManager;
            _tokenProvider = tokenProvider;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var applications = _context.Applications.Where(a => a.User == user).ToList();
            var domainName = Request.Host + (Request.Host.Port != null ? "" : ":" + Request.Host.Port);
            return View(new IndexViewModel {DomainName = domainName, Applications = applications});
        }


        public IActionResult Create()
        {
            return View(new CreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                var application = new Application
                {
                    Name = model.Name,
                    LoginCallbackUrl = model.LoginCallbackUrl,
                    Token = Guid.NewGuid(),
                    Secret = model.Secret,
                    ValidFor = model.ValidFor,
                    ExtendExpiryOnRequest = model.ExtendExpiryOnRequest
                };
                _context.Applications.Add(application);
                var contextUser = _context.ApplicationUser.First(u => u.Id == user.Id);
                contextUser.Applications.Add(application);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [Route("Application/Delete/{applicationId}")]
        public async Task<IActionResult> Delete(int applicationId)
        {
            if (!ModelState.IsValid) return RedirectToAction(nameof(Index));

            var applicationToRemove = _context.Applications.FirstOrDefault(a => a.Id == applicationId);
            if (applicationToRemove == null) return RedirectToAction(nameof(Index));

            var user = await _userManager.GetUserAsync(User);
            if (user != applicationToRemove.User) return RedirectToAction(nameof(Index));

            var auhalRemove =
                _context.ApplicationUserHasAuthLevels.Where(auhaul => auhaul.App.Id == applicationToRemove.Id);
            _context.ApplicationUserHasAuthLevels.RemoveRange(auhalRemove);

            _context.Applications.Remove(_context.Applications.First(a => a.Id == applicationId));
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Route("Application/Update/{applicationId}")]
        public async Task<IActionResult> Update(int applicationId)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Index));

            var app = _context.Applications.FirstOrDefault(a => a.Id == applicationId);

            if (app == null)
                return RedirectToAction(nameof(Index));
            var user = await _userManager.GetUserAsync(User);
            if (user == app.User)
                return
                    View(new UpdateViewModel
                    {
                        Name = app.Name,
                        Secret = app.Secret,
                        LoginCallbackUrl = app.LoginCallbackUrl,
                        Token = app.Token.ToString(),
                        ValidFor = app.ValidFor,
                        ExtendExpiryOnRequest = app.ExtendExpiryOnRequest
                    });

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Application/Update/{applicationId}")]
        public async Task<IActionResult> Update(UpdateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Token.Equals(Guid.Parse(model.Token)));
            if (app == null) return RedirectToAction(nameof(Index));

            var user = await _userManager.GetUserAsync(User);
            if (user != app.User) return RedirectToAction(nameof(Index));

            app.Name = model.Name;
            app.LoginCallbackUrl = model.LoginCallbackUrl;
            app.Secret = model.Secret;
            app.ValidFor = model.ValidFor;
            app.ExtendExpiryOnRequest = model.ExtendExpiryOnRequest;

            _context.Applications.Update(app);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Route("Application/EditUserAuthLevels/{applicationId}")]
        public async Task<IActionResult> EditUserAuthLevels(string applicationId)
        {
            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Id.ToString() == applicationId);
            if (app == null) return RedirectToAction(nameof(Index));

            app.ApplicationUsersHasAuthLevels =
                _context.ApplicationUserHasAuthLevels.Where(auhal => auhal.App.Id == app.Id).ToList();

            return
                View(new EditUserAuthLevelsViewModel
                {
                    Application = app
                });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Application/EditUserAuthLevels/{applicationId}")]
        public async Task<IActionResult> EditUserAuthLevels(string applicationId,
            ApplicationUserHasAuthLevel[] authLevels)
        {
            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Id.ToString() == applicationId);
            if (app == null) return RedirectToAction(nameof(Index));

            app.ApplicationUsersHasAuthLevels =
                _context.ApplicationUserHasAuthLevels.Where(auhal => auhal.App.Id == app.Id).ToList();

            _context.ApplicationUserHasAuthLevels.RemoveRange(app.ApplicationUsersHasAuthLevels);
            app.ApplicationUsersHasAuthLevels.Clear();

            _context.ApplicationUserHasAuthLevels.AddRange(authLevels);
            app.ApplicationUsersHasAuthLevels.AddRange(authLevels);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

src/SignInAppTest/Controllers/StaticContentController.cs
using Microsoft.AspNetCore.Mvc;

namespace DaVinciCollegeAuthenticationService.Controllers
{
    public class StaticContentController : Controller
    {
        public IActionResult PageNotFound()
        {
            return View();
        }

        [Route("/Documentation")]
        public IActionResult Documentation()
        {
            return View();
        }
    }
}

src/SignInAppTest/Views/Shared/_Layout.cshtml
@using DaVinciCollegeAuthenticationService.Models
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DaVinci AS</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @*<link rel="stylesheet" href="~/css/creative.css" />*@
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css"/>
        <link rel="stylesheet" href="lib/bootstrap3-dialog/dist/css/bootstrap-dialog.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DaVinci Authorization Service</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home fa-fw" aria-hidden="true"></i>Home</a></li>
                    <li><a asp-area="" asp-controller="StaticContent" asp-action="Documentation"><i class="fa fa-file-text fa-fw" aria-hidden="true"></i>Documentatie</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Application" asp-action="Index"><i class="fa fa-rocket fa-fw" aria-hidden="true"></i>Applicaties</a></li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li><a asp-area="" asp-controller="AdminPanel" asp-action="Index"><i class="fa fa-user-md fa-fw" aria-hidden="true"></i>Admin Panel</a></li>
                        }
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - DaVinci Authorization Service</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap3-dialog/dist/js/bootstrap-dialog.js"></script>
        @*<script src="~/js/creative.js"></script>*@
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover();
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>