src/SignInAppTest/Models/Application.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DaVinciCollegeAuthenticationService.Models
{
    public class Application
    {
        public Application()
        {
            ApplicationUsersHasAuthLevels = new List<ApplicationUserHasAuthLevel>();
        }
        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<ApplicationUserHasAuthLevel> ApplicationUsersHasAuthLevels { get; set; }

        public int Id { get; set; }

        [MinLength(5)]
        [MaxLength(100)]
        public string Name { get; set; }

        //[Display(Name = "Secret Code")]
        [MinLength(5)]
        [MaxLength(100)]
        public string Secret { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Token { get; set; }

        [DataType(DataType.Url)]
        public string LoginCallbackUrl { get; set; }

        [DataType(DataType.Duration)]
        public int ValidFor { get; set; }

        public bool ExtendExpiryOnRequest { get; set; }
    }
}

src/SignInAppTest/Models/ApplicationViewModels/EditUserAuthLevelsViewModel.cs
namespace DaVinciCollegeAuthenticationService.Models.ApplicationViewModels
{
    public class EditUserAuthLevelsViewModel
    {
        public Application Application { get; set; }
    }
}

src/SignInAppTest/Controllers/ApplicationController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DaVinciCollegeAuthenticationService.Data;
using DaVinciCollegeAuthenticationService.Models;
using DaVinciCollegeAuthenticationService.Models.ApplicationViewModels;
using DaVinciCollegeAuthenticationService.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;

namespace DaVinciCollegeAuthenticationService.Controllers
{
    [Authorize]
    public class ApplicationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ITokenProvider _tokenProvider;
        private readonly UserManager<ApplicationUser> _userManager;

        public ApplicationController(UserManager<ApplicationUser> userManager, ApplicationDbContext context,
            ITokenProvider tokenProvider)
        {
            _context = context;
            _userManager = userManager;
            _tokenProvider = tokenProvider;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var applications = _context.Applications.Where(a => a.User == user).ToList();
            var domainName = Request.Host + (Request.Host.Port != null ? "" : ":" + Request.Host.Port);
            return View(new IndexViewModel {DomainName = domainName, Applications = applications});
        }


        public IActionResult Create()
        {
            return View(new CreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                var application = new Application
                {
                    Name = model.Name,
                    LoginCallbackUrl = model.LoginCallbackUrl,
                    Token = Guid.NewGuid(),
                    Secret = model.Secret,
                    ValidFor = model.ValidFor,
                    ExtendExpiryOnRequest = model.ExtendExpiryOnRequest
                };
                _context.Applications.Add(application);
                var contextUser = _context.ApplicationUser.First(u => u.Id == user.Id);
                contextUser.Applications.Add(application);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [Route("Application/Delete/{applicationId}")]
        public async Task<IActionResult> Delete(int applicationId)
        {
            if (!ModelState.IsValid) return RedirectToAction(nameof(Index));

            var applicationToRemove = _context.Applications.FirstOrDefault(a => a.Id == applicationId);
            if (applicationToRemove == null) return RedirectToAction(nameof(Index));

            var user = await _userManager.GetUserAsync(User);
            if (user != applicationToRemove.User) return RedirectToAction(nameof(Index));

            var auhalRemove =
                _context.ApplicationUserHasAuthLevels.Where(auhaul => auhaul.App.Id == applicationToRemove.Id);
            _context.ApplicationUserHasAuthLevels.RemoveRange(auhalRemove);

            _context.Applications.Remove(_context.Applications.First(a => a.Id == applicationId));
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Route("Application/Update/{applicationId}")]
        public async Task<IActionResult> Update(int applicationId)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Index));

            var app = _context.Applications.FirstOrDefault(a => a.Id == applicationId);

            if (app == null)
                return RedirectToAction(nameof(Index));
            var user = await _userManager.GetUserAsync(User);
            if (user == app.User)
                return
                    View(new UpdateViewModel
                    {
                        Name = app.Name,
                        Secret = app.Secret,
                        LoginCallbackUrl = app.LoginCallbackUrl,
                        Token = app.Token.ToString(),
                        ValidFor = app.ValidFor,
                        ExtendExpiryOnRequest = app.ExtendExpiryOnRequest
                    });

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Application/Update/{applicationId}")]
        public async Task<IActionResult> Update(UpdateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Token.Equals(Guid.Parse(model.Token)));
            if (app == null) return RedirectToAction(nameof(Index));

            var user = await _userManager.GetUserAsync(User);
            if (user != app.User) return RedirectToAction(nameof(Index));

            app.Name = model.Name;
            app.LoginCallbackUrl = model.LoginCallbackUrl;
            app.Secret = model.Secret;
            app.ValidFor = model.ValidFor;
            app.ExtendExpiryOnRequest = model.ExtendExpiryOnRequest;

            _context.Applications.Update(app);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Route("Application/EditUserAuthLevels/{applicationId}")]
        public async Task<IActionResult> EditUserAuthLevels(string applicationId)
        {
            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Id.ToString() == applicationId);
            if (app == null) return RedirectToAction(nameof(Index));

            app.ApplicationUsersHasAuthLevels =
                _context.ApplicationUserHasAuthLevels.Where(auhal => auhal.App.Id == app.Id).ToList();

            return
                View(new EditUserAuthLevelsViewModel
                {
                    Application = app
                });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Application/EditUserAuthLevels/{applicationId}")]
        public async Task<IActionResult> EditUserAuthLevels(string applicationId,
            ApplicationUserHasAuthLevel[] authLevels)
        {
            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Id.ToString() == applicationId);
            if (app == null) return RedirectToAction(nameof(Index));

            app.ApplicationUsersHasAuthLevels =
                _context.ApplicationUserHasAuthLevels.Where(auhal => auhal.App.Id == app.Id).ToList();

            _context.ApplicationUserHasAuthLevels.RemoveRange(app.ApplicationUsersHasAuthLevels);
            app.ApplicationUsersHasAuthLevels.Clear();

            _context.ApplicationUserHasAuthLevels.AddRange(authLevels);
            app.ApplicationUsersHasAuthLevels.AddRange(authLevels);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

src/SignInAppTest/Controllers/SsoController.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using DaVinciCollegeAuthenticationService.Data;
using DaVinciCollegeAuthenticationService.Models;
using DaVinciCollegeAuthenticationService.Models.SsoViewModels;
using Jose;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;

namespace DaVinciCollegeAuthenticationService.Controllers
{
    public class SsoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public SsoController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        ///     Provides a login page for the given app
        /// </summary>
        /// <param name="token">The token associated with the app</param>
        /// <returns></returns>
        [AllowAnonymous]
        [Route("Sso/Login/{token}")]
        public async Task<IActionResult> Login(string token, string returnUrl)
        {
            Guid guid;
            if (!Guid.TryParse(token, out guid)) return View(null);

            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Token.Equals(guid));
            if (app == null)
                return View("InvalidLoginToken");

            var model = new LoginViewModel {Application = app, ReturnUrl = returnUrl};
            return _signInManager.IsSignedIn(User) ? View("LoginContinue", model) : View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Sso/Login/{token}")]
        public async Task<IActionResult> LoginPost(string userNumber, string password, string token, string returnUrl)
        {
            Guid guid;
            if (!Guid.TryParse(token, out guid))
                return BadRequest();

            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Token.Equals(guid));

            var result = await _signInManager.PasswordSignInAsync(userNumber, password, true, false);
            if (!result.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "Inloggen mislukt.");
                return RedirectToAction("Login", new {token});
            }

            var authLevel =
                await _context.ApplicationUserHasAuthLevels.FirstOrDefaultAsync(
                    auhal => (auhal.App.Id == app.Id) && (auhal.UserNumber == userNumber));

            var user = await _context.ApplicationUser.FirstOrDefaultAsync(u => u.UserName == userNumber);
            var payload = new Dictionary<string, object>
            {
                {"userNumber", userNumber},
                {"firstName", user.Firstname},
                {"prefix", user.Prefix},
                {"lastName", user.Lastname},
                {"expiry", DateTime.Now.AddSeconds(app.ValidFor).Ticks.ToString()},
                {
                    "authLevel", authLevel?.AuthLevel ?? 1
                }
            };

            var secretKey = Encoding.UTF8.GetBytes(app.Secret);
            var jwt = JWT.Encode(payload, secretKey, JwsAlgorithm.HS256);

            _context.Accesstokens.Add(new Accesstoken {App = app, Token = jwt, ValidTill = DateTime.Now.AddSeconds(app.ValidFor)});
            await _context.SaveChangesAsync();

            var parametersToAdd = new Dictionary<string, string>
            {
                {"token", jwt}
            };

            if (returnUrl != null)
                parametersToAdd.Add("returnUrl", returnUrl);

            var url = QueryHelpers.AddQueryString(app.LoginCallbackUrl, parametersToAdd);
            return RedirectPermanent(url);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Sso/LoginContinue")]
        public async Task<IActionResult> LoginContinue(string token, string returnUrl)
        {
            Guid guid;
            if (!Guid.TryParse(token, out guid))
                return BadRequest();

            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Token.Equals(guid));
            if (app == null) return BadRequest();

            var authLevel =
                await _context.ApplicationUserHasAuthLevels.FirstOrDefaultAsync(
                    auhal => (auhal.App.Id == app.Id) && (auhal.UserNumber == User.Identity.Name));


            var user = await _context.ApplicationUser.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            var payload = new Dictionary<string, object>
            {
                {"userNumber", User.Identity.Name},
                {"firstName", user.Firstname},
                {"prefix", user.Prefix},
                {"lastName", user.Lastname},
                {"expiry", DateTime.Now.AddSeconds(app.ValidFor).Ticks.ToString()},
                {
                    "authLevel", authLevel?.AuthLevel ?? 1
                }
            };

            var secretKey = Encoding.UTF8.GetBytes(app.Secret);
            var jwt = JWT.Encode(payload, secretKey, JwsAlgorithm.HS256);

            _context.Accesstokens.Add(new Accesstoken {App = app, Token = jwt, ValidTill = DateTime.Now.AddSeconds(app.ValidFor)});
            await _context.SaveChangesAsync();

            var parametersToAdd = new Dictionary<string, string>
            {
                {"token", jwt}
            };

            if (returnUrl != null)
                parametersToAdd.Add("returnUrl", returnUrl);

            var url = QueryHelpers.AddQueryString(app.LoginCallbackUrl, parametersToAdd);
            return RedirectPermanent(url);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Sso/Logout")]
        public async Task<IActionResult> Logout(string token)
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login", new {token});
        }

        public async Task<IActionResult> Cancel(string token)
        {
            Guid guid;
            if (!Guid.TryParse(token, out guid))
                return BadRequest();

            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Token.Equals(guid));
            if (app == null) return BadRequest();

            var parametersToAdd = new Dictionary<string, string>
            {
                {"err", "canceled"}
            };

            var url = QueryHelpers.AddQueryString(app.LoginCallbackUrl, parametersToAdd);
            return RedirectPermanent(url);
        }

        [Route("Sso/ValidateAuth/{appId}/{token}")]
        public async Task<IActionResult> ValidateAuth(string appId, string token)
        {
            Guid guid;
            if (!Guid.TryParse(appId, out guid))
                return Json(new {err = "Invalid AppId"});

            var app = await _context.Applications.FirstOrDefaultAsync(a => a.Token.Equals(guid));
            if (app == null) return Json(new {err = "Invalid AppId"});

            var accessToken = await _context.Accesstokens.FirstOrDefaultAsync(at => at.Token == token);
            if (accessToken == null) return Json(new {err = "Invalid Accesstoken"});

            if (!accessToken.App.Token.Equals(guid)) Json(new {err = "AppId doesn't match with Accesstoken"});

            var secretKey = Encoding.UTF8.GetBytes(app.Secret);

            var data = JWT.Decode<Dictionary<string, dynamic>>(token, secretKey, JwsAlgorithm.HS256);

            // Expiry is still not reached?
            if (accessToken.ValidTill > DateTime.Now)
            {
                if (!app.ExtendExpiryOnRequest) return Json(new {token});

                data["expiry"] = DateTime.Now.AddSeconds(app.ValidFor).Ticks.ToString();
                token = JWT.Encode(data, secretKey, JwsAlgorithm.HS256);
                accessToken.Token = token;
                accessToken.ValidTill = DateTime.Now.AddSeconds(app.ValidFor);
                await _context.SaveChangesAsync();
                return Json(new {token});
            }
            _context.Accesstokens.Remove(accessToken);
            await _context.SaveChangesAsync();

            return Json(new {err = "expired"});
        }
    }
}

src/SignInAppTest/Views/Application/Create.cshtml
@model DaVinciCollegeAuthenticationService.Models.ApplicationViewModels.CreateViewModel

<div class="row col-md-offset-2">
    <div class="col-md-10">
        <h2>Voeg een nieuwe applicatie toe</h2>
        <form asp-controller="Application" asp-action="Create" method="post" class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Secret" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Secret" class="form-control" />
                    <span asp-validation-for="Secret" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="LoginCallbackUrl" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="LoginCallbackUrl" placeholder="Vb: http://www.mijnapp.nl/loginCallback" class="form-control"/>
                    <span asp-validation-for="LoginCallbackUrl" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ValidFor" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="ValidFor" class="form-control" />
                    <span asp-validation-for="ValidFor" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ExtendExpiryOnRequest" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="ExtendExpiryOnRequest" style="height:32px; width:32px" class="form-control" />
                    <span asp-validation-for="ExtendExpiryOnRequest" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">Toevoegen</button>
                </div>
            </div>
        </form>
    </div>
</div>

src/SignInAppTest/Views/Application/EditUserAuthLevels.cshtml
@model DaVinciCollegeAuthenticationService.Models.ApplicationViewModels.EditUserAuthLevelsViewModel

<div class="row col-md-offset-2">
    <div class="col-md-10">
        <h2>Verander het authorisatie niveau van specifieke gebruikers</h2>
        <hr/>
        <button id="addNewAuthLevelButton" class="btn btn-default">Voeg nieuwe authorisatie regel toe</button>
        <button id="sendFormButton" class="btn btn-primary">Opslaan</button>
        <form id="editUserAuthLevelsForm" asp-controller="Application" asp-action="EditUserAuthLevels" method="post" class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="submit" class="hidden"/>
            @for (var i = 0; i < Model.Application.ApplicationUsersHasAuthLevels.Count; i++)
            {
                <div class="form-group" style="border: 1px solid #000; padding: 5px;">
                    <input type="text" class="form-control col-sm-4" name="authLevels[@i].UserNumber" placeholder="99020000" value="@Model.Application.ApplicationUsersHasAuthLevels.ToArray()[i].UserNumber" required />
                    <input type="number" class="form-control col-sm-8" name="authLevels[@i].AuthLevel" placeholder="Een getal dat aangeeft welk auth niveau de gebruiker heeft" min="0" value="@Model.Application.ApplicationUsersHasAuthLevels.ToArray()[i].AuthLevel" required/>
                    <button class="btn btn-danger" onclick="$(this).parent().remove()">Regel Verwijderen</button>
                </div>
            }
        </form>
    </div>
</div>

@section scripts
{
    <script>
        $(function() {
            $("#sendFormButton").click(function() {
                $("#editUserAuthLevelsForm").find('[type="submit"]').trigger('click');
            });

            $("#addNewAuthLevelButton")
                .click(function() {
                    var index = $("#editUserAuthLevelsForm div.form-group").size();
                    $("#editUserAuthLevelsForm")
                        .append("<div class=\"form-group\" style=\"border: 1px solid #000; padding: 5px;\"> <input type=\"text\" class=\"form-control col-sm-4\" name=\"authLevels[" + index + "].UserNumber\" placeholder=\"99020000\" required /> <input type=\"number\" class=\"form-control col-sm-8\" name=\"authLevels[" + index + "].AuthLevel\" placeholder=\"1\" min=\"0\" max=\"5\" required/> <button class=\"btn btn-danger\" onclick=\"$(this).parent().remove()\">Regel Verwijderen</button> </div>");
                });
        });
    </script>
}

src/SignInAppTest/Views/Application/Index.cshtml
@model DaVinciCollegeAuthenticationService.Models.ApplicationViewModels.IndexViewModel
<h1><i class="fa fa-rocket fa-fw" aria-hidden="true"></i>Applicaties</h1>
<div class="jumbotron">
    <a class="btn btn-success" asp-controller="Application" asp-action="Create"><i class="fa fa-plus fa-fw" aria-hidden="true"></i>Applicatie Toevoegen</a>
    <hr />
    @if (Model.Applications.Count > 0)
    {
        @foreach (var application in Model.Applications)
        {
             <div class="panel panel-default">
                 <div class="panel-body">
                     <p style="display:inline-block;">@application.Name</p>
                     @*<hr />*@
                     <button class="btn btn-danger" style="float:right;" onclick="removePrompt(function (confirmed) { if (confirmed) { window.location.replace('@Url.Action("Delete", new { Id = application.Id })'); } })"><i class="fa fa-remove fa-fw" aria-hidden="true"></i>Verwijder</button>
                     <a asp-controller="Application" asp-action="Update" asp-route-applicationId="@application.Id" class="btn btn-warning" style="display:inline-block; float:right;"><i class="fa fa-edit fa-fw" aria-hidden="true"></i>Bewerken</a>
                     <a asp-controller="Application" asp-action="EditUserAuthLevels" asp-route-applicationId="@application.Id" class="btn btn-default" style="display:inline-block; float:right;"><i class="fa fa-key fa-fw" aria-hidden="true"></i>Auth Niveau's</a>
                     <div class="input-group">
                         <input class="form-control ssoLoginLink" style="max-width: 520px" type="text" readonly="readonly" value="http://@Model.DomainName@Url.Action("Login", "Sso", new { Token = application.Token.ToString() })" />
                         <span class="input-group-btn">
                            <button class="btn btn-primary" style="float: left;" id="copyBtn" onclick="copyToClipBoard($(this).parent().parent().children('.ssoLoginLink'))" type="button"><i class="fa fa-clipboard fa-fw" aria-hidden="true"></i>Login Link Kopiëren</button>
                        </span>
                     </div>
                     <div style="padding: 10px;"></div>
                     <div class="input-group">
                         <input class="form-control ssoAuthValidationLink" style="max-width: 520px" type="text" readonly="readonly" value="http://@Model.DomainName/Sso/ValidateAuth/@application.Token.ToString()/[ACCESS_TOKEN]" />
                         <span class="input-group-btn">
                             <button class="btn btn-primary" style="float: left;" id="copyBtn" onclick="copyToClipBoard($(this).parent().parent().children('.ssoAuthValidationLink'))" type="button"><i class="fa fa-clipboard fa-fw" aria-hidden="true"></i>Validatie Link Kopiëren</button>
                         </span>
                     </div>
                 </div>
             </div>
         }
    }
    else
    {
        <p>Geen applicaties</p>   
    }
</div>

src/SignInAppTest/Views/Application/Update.cshtml
@model DaVinciCollegeAuthenticationService.Models.ApplicationViewModels.UpdateViewModel

<h1>Bewerken</h1>
<div class="col-md-8">
    <form asp-controller="Application" asp-action="Update" method="post" class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Secret" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Secret" class="form-control" />
                <span asp-validation-for="Secret" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LoginCallbackUrl" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LoginCallbackUrl" class="form-control" />
                <span asp-validation-for="LoginCallbackUrl" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ValidFor" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ValidFor" class="form-control" />
                <span asp-validation-for="ValidFor" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ExtendExpiryOnRequest" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ExtendExpiryOnRequest" style="height:32px; width:32px" class="form-control" />
                <span asp-validation-for="ExtendExpiryOnRequest" class="text-danger"></span>
            </div>
        </div>
        <input asp-for="Token" type="hidden"/>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-default">Aanpassen</button>
            </div>
        </div>
    </form>
</div>